version: "3"

services:
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#      args:
#        - CHANGE_SOURCE=true
#    container_name: nginx
#    #image: docker-ss/nginx:latest ##定义<build image name>
#    restart: always
#    volumes:
#      - ./nginx/log:/var/log/nginx
#      - ./nginx/site.conf:/etc/nginx/sites-available
#      - ./nginx/ssl:/etc/nginx/ssl
#    networks:
#      - server-network
#    ports:
#      - "80:80"
#      - "443:443"
#      - "8081:8081"

#  nginx-proxy-manager:
#    image: 'jc21/nginx-proxy-manager:latest'
#    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '8081:81'
#      - '443:443'
#    volumes:
#      - ./nginx-proxy-manager/data:/data
#      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  nginxWebUi-server:
    image: cym1102/nginxwebui:latest
    volumes:
      - type: bind
        source: "./nginxWebUI"
        target: "./nginxWebUI"
    environment:
      BOOT_OPTIONS: "--server.port=8081"
    privileged: true
    network_mode: "host"

  portainer:
    image:  portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9001:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

networks:
  server-network: