version: "3"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - data-network
    depends_on:
      - mysql
      #- memcached
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
    #  PMA_HOST: mysql
    #  PMA_USER: root
    #  PMA_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=shanchuang2023A. # root管理员用户密码 用户名默认root
      #MYSQL_DEV_USER: developer   # 创建developer用户
      #MYSQL_DEV_PASSWORD: developer  # 设置developer用户的密码
      #- MYSQL_DATABASE=developer
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=UTC
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - data-network
    ports:
      - "3306:3306"

  redis:
    image: redis:5.0-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass shanchuang2023A.
    volumes:
      - ./redis/data:/data
#    networks:
#      - data-network
    ports:
      - "6379:6379"

  php-redis-admin:
    image: erikdubbelboer/phpredisadmin
    #image: phpredisadmin/phpredisadmin
    container_name: php-redis-admin
    restart: always
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: root
      REDIS_1_AUTH: shanchuang2023A.
      LOGIN_ENABLED: "true"
#    networks:
#      - data-network
    ports:
      - "9002:80"

#  memcached:
#    image: memcached
#    container_name: memcached
#    networks:
#      - data-network
#    expose:
#      - "11211"

#networks:
#  data-network: