version: "3"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
      #- memcached
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 80M
    #  PMA_HOST: mysql
    #  PMA_USER: root
    #  PMA_PASSWORD: root

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root管理员用户密码 用户名默认root
      #MYSQL_DEV_USER: developer   # 创建developer用户
      #MYSQL_DEV_PASSWORD: developer  # 设置developer用户的密码
      #- MYSQL_DATABASE=developer
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=UTC
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:5.0-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass 123456
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"

  php-redis-admin:
    image: erikdubbelboer/phpredisadmin
    #image: phpredisadmin/phpredisadmin
    container_name: php-redis-admin
    restart: always
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: root
      REDIS_1_AUTH: shanchuang2023A.
      LOGIN_ENABLED: "true"
    ports:
      - "9002:80"

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  portainer:
      image: portainer/portainer
      container_name: portainer
      restart: always
      ports:
        - "9001:9000"
      command: -H unix:///var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer/data:/data

#  memcached:
#    image: memcached
#    container_name: memcached
#    networks:
#      - data-network
#    expose:
#      - "11211"
